# Generated by Django 6.0.6 on 2026-06-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0002_alter_genre_name_alter_movie_title_alter_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_overall_rating',
            field=models.FloatField(default=5.5, verbose_name='Overall Rating'),
        ),
    ]
